#include <assert.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>

#include <string.h>

#include "line_error.h"
#include "encode_instruction.h"
#include "parsing.h"
#include "string_slice.h"
#include "string_to_int_map.h"

#include "gperf/perfect_hash.h"

const StringSlice TOKEN_COMMA         = (StringSlice){ .length = 1, .bytes = "," };
const StringSlice TOKEN_OPEN_BRACKET  = (StringSlice){ .length = 1, .bytes = "[" };
const StringSlice TOKEN_CLOSE_BRACKET = (StringSlice){ .length = 1, .bytes = "]" };

constexpr size_t  UINT32_BITS = sizeof(uint32_t) * CHAR_BIT;
constexpr size_t  INT32_BITS  = sizeof(int32_t)  * CHAR_BIT;

// ================================================================
//  Encode M-Type
// ================================================================

constexpr size_t   M_OFFSET_BASE = 0;
constexpr size_t   M_OFFSET_BITS = 8;
constexpr uint32_t M_OFFSET_MASK = 0xFF;
constexpr size_t   M_SHAMT_BASE  = 8;
constexpr size_t   M_SHAMT_MAX   = 15;
constexpr uint32_t M_U           = 1u << 12;
constexpr uint32_t M_ST          = 1u << 13;
constexpr uint32_t M_W           = 1u << 14;
constexpr uint32_t M_I           = 1u << 15;
constexpr size_t   M_RS1_BASE    = 16;
constexpr uint32_t M_B           = 1u << 21;
constexpr uint32_t M_H           = 1u << 22;
constexpr uint32_t M_SB          = 1u << 23;
constexpr size_t   M_RD_BASE     = 24;
constexpr uint32_t M_OPCODE      = 0b000 << 29;

constexpr int64_t M_MAX_OFFSET = (1 << M_OFFSET_BITS) - 1;
constexpr int64_t M_MIN_OFFSET = -M_MAX_OFFSET - 1;

constexpr size_t M_OFFSET_SIGN_BITS = UINT32_BITS - M_OFFSET_BITS;

static void calculate_offset_and_shift_m_type(int64_t value, int64_t* offset, int64_t* shamt, LineError* err) {
    if (value >= 0) {
        if (value > UINT32_MAX) goto EXCEEDS_REGISTER_WIDTH;

        uint32_t value_uint32 = (uint32_t)value;
        size_t leading_ones = __builtin_clz(~value_uint32);

        if (value <= M_MAX_OFFSET || leading_ones >= M_OFFSET_SIGN_BITS) {
            *offset = value;
            *shamt = 0;
            return;
        }

        size_t trailing_zeros = __builtin_ctz(value_uint32);
        size_t leading_zeros = __builtin_clz(value_uint32);
        size_t window_size = UINT32_BITS - leading_zeros - trailing_zeros;

        if (window_size <= M_OFFSET_BITS) {
            *shamt = M_OFFSET_SIGN_BITS - leading_zeros;
            if (*shamt > M_SHAMT_MAX) goto EXCEEDS_MAXIMUM_SHIFT;
            *offset = value_uint32 >> *shamt;
            assert(*offset <= M_MAX_OFFSET);
            return;
        }

        // Encode unsigned values that can be generated by abusing sign extentions.
        // For example: 0xFFFEA800      (or 0b1111_1111_1111_1110_1010_1000_0000_0000) can be encoded as
        //              0xFFFFFF54 << 9 (or 0b1111_1111_1111_1111_1111_1111_0101_0100 << 9).
        if (leading_zeros == 0) {
            // test whether there are enough leading zeros to accomodate the value
            *shamt = M_OFFSET_SIGN_BITS - leading_ones;
            assert(*shamt >= 0);
            if (*shamt < trailing_zeros) {
                *offset = value_uint32 >> *shamt;
                return;
            }
        }

        goto NOT_ENCODABLE;

    } else {
        if (value < INT32_MIN) goto EXCEEDS_REGISTER_WIDTH;

        if (value >= M_MIN_OFFSET) {
            *offset = value;
            *shamt = 0;
            return;
        }

        int32_t value_int32 = (int32_t)value;

        size_t trailing_zeros = __builtin_ctz(value_int32);
        size_t leading_ones = __builtin_clz(~value_int32);
        size_t window_size = INT32_BITS - leading_ones - trailing_zeros;

        if (window_size > M_OFFSET_BITS) goto NOT_ENCODABLE;

        *shamt = M_OFFSET_SIGN_BITS - leading_ones;
        assert(*shamt >= 0);
        if (*shamt > M_SHAMT_MAX) goto EXCEEDS_MAXIMUM_SHIFT;
        *offset = value_int32 >> *shamt;
        assert(*offset > M_MIN_OFFSET);
        return;
    }

EXCEEDS_REGISTER_WIDTH:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "offset exceeds register width",
        },
    };
    return;

EXCEEDS_MAXIMUM_SHIFT:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "offset encoding exceeds maximum shift amount for M-Type instructions",
        },
    };
    return;

NOT_ENCODABLE:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "offset is not encodable with 9 bit sign extended integer and shift",
        },
    };
    return;
}

Instruction encode_m_type(Tokenizer* line, uint32_t flags, StringToIntMap* defines, LineError* err) {
    StringSlice token = {};
    bool eol = false;

    uint32_t machine_word = M_OPCODE|flags;

    machine_word |= expect_register(line, err) << M_RD_BASE;
    if (err->error_tag) return (Instruction){};

    if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};
    if (!expect_token(line, TOKEN_OPEN_BRACKET, err)) return (Instruction){};
   
    machine_word |= expect_register(line, err) << M_RS1_BASE;
    if (err->error_tag) return (Instruction){};
  
    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
            },
        };
        return (Instruction){};
    }

    switch (token.bytes[0]) {
    case ']': goto WRITEBACK;
    case ',': break;
    default:
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
                .found = found_token_string(token),
            },
        };
        return (Instruction){};
    }

    // Save state of Tokenizer in case offset is immediate
    Tokenizer tokenizer_at_offset_start = *line;

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "register or expression",
            },
        };
        return (Instruction){};
    }

    int64_t offset = 0;
    int64_t shamt = 0;
    bool negative_offset = false;
    size_t offset_start_column = line->token_start;

    if (token.bytes[0] == '-') {
        negative_offset = true;
        eol = tokenizer_next(line, &token, err);
        if (err->error_tag) return (Instruction){};
        if (eol) {
            *err = (LineError){
                .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
                .unexpected_token = (LineErrorUnexpectedToken){
                    .column = line->token_start,
                    .expected = "register or expression",
                },
            };
            return (Instruction){};
        }
    }

    if (!parse_register(token, (uint64_t*)&offset)) {
        *line = tokenizer_at_offset_start;

        offset = parse_expression(line, err, defines);
        if (err->error_tag) return (Instruction){};

        calculate_offset_and_shift_m_type(offset, &offset, &shamt, err);
        if (err->error_tag) {
            err->not_encodable.start_column = offset_start_column;
            err->not_encodable.end_column = line->token_end;
            return (Instruction){};
        }

        machine_word |= M_I;
        machine_word |= (offset & M_OFFSET_MASK) << M_OFFSET_BASE;
        machine_word |= ((offset >> M_OFFSET_BITS) & 1) ? M_SB : 0;
        machine_word |= shamt << M_SHAMT_BASE;

        if (!expect_token(line, TOKEN_CLOSE_BRACKET, err)) return (Instruction){};

        goto WRITEBACK;
    }

    machine_word |= (negative_offset) ? M_SB : 0;
    machine_word |= offset << M_OFFSET_BASE;

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
            },
        };
        return (Instruction){};
    }

    switch (token.bytes[0]) {
    case ']': goto WRITEBACK;
    case 's': if (token.length == 3 && token.bytes[1] == 'l' && token.bytes[2] == 'l') break;
    default:
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
                .found = found_token_string(token),
            },
        };
        return (Instruction){};
    }

    size_t shift_start_column = tokenizer_next_token_start(line);
    shamt = parse_expression(line, err, defines);
    if (err->error_tag) return (Instruction){};
    if (shamt < 0) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NEGATIVE_SHIFT_AMOUNT,
            .negative_shift_amount = (LineErrorNegativeShiftAmount){
                .start_column = shift_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    if (shamt > M_SHAMT_MAX) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "shift value exceeds maximum shift amount for M-Type instructions",
                .start_column = shift_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    machine_word |= shamt << M_SHAMT_BASE;

    if (!expect_token(line, TOKEN_CLOSE_BRACKET, err)) return (Instruction){};

WRITEBACK:
    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) return (Instruction){ .machine_word = machine_word };

    if (token.bytes[0] != '!') {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "'eol'",
            }
        };
        return (Instruction){};
    }
    machine_word |= M_W;

    return (Instruction){ .machine_word = machine_word };
}

// ================================================================
//  Encode Instruction
// ================================================================

Instruction encode_instruction(Tokenizer* line, StringToIntMap* defines, LineError* err) {
    StringSlice token = {};
    bool eol = tokenizer_next(line, &token, err);
    if (eol) return (Instruction){};

    Mnemonic mnem = parse_mnemonic(token);

    Instruction encoding = (Instruction){};
    switch (mnem) {
        // M-Type
        case MN_LW:  encoding = encode_m_type(line, 0,        defines, err); break;
        case MN_LB:  encoding = encode_m_type(line, M_B,      defines, err); break;
        case MN_LH:  encoding = encode_m_type(line, M_H,      defines, err); break;
        case MN_LBU: encoding = encode_m_type(line, M_B|M_U,  defines, err); break;
        case MN_LHU: encoding = encode_m_type(line, M_H|M_U,  defines, err); break;
        case MN_SW:  encoding = encode_m_type(line, M_ST,     defines, err); break;
        case MN_SB:  encoding = encode_m_type(line, M_ST|M_B, defines, err); break;
        case MN_SH:  encoding = encode_m_type(line, M_ST|M_H, defines, err); break;
        default: return (Instruction){};
    }

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (!eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "'eol'",
                .found = found_token_string(token),
            },
        };
        return (Instruction){};
    }

    return encoding;
}

