#include <assert.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>

#include <string.h>

#include "line_error.h"
#include "encode_instruction.h"
#include "parsing.h"
#include "string_slice.h"
#include "string_to_int_map.h"

#include "gperf/perfect_hash.h"

const StringSlice TOKEN_COMMA         = (StringSlice){ .length = 1, .bytes = "," };
const StringSlice TOKEN_OPEN_BRACKET  = (StringSlice){ .length = 1, .bytes = "[" };
const StringSlice TOKEN_CLOSE_BRACKET = (StringSlice){ .length = 1, .bytes = "]" };

constexpr size_t  UINT32_BITS = sizeof(uint32_t) * CHAR_BIT;
constexpr size_t  INT32_BITS  = sizeof(int32_t)  * CHAR_BIT;

// ================================================================
//  Encode M-Type
// ================================================================

constexpr size_t   M_OFFSET_BASE = 0;
constexpr size_t   M_OFFSET_BITS = 8;
constexpr uint32_t M_OFFSET_MASK = 0xFF;
constexpr size_t   M_SHAMT_BASE  = 8;
constexpr size_t   M_SHAMT_MAX   = 15;
constexpr uint32_t M_U           = 1u << 12;
constexpr uint32_t M_ST          = 1u << 13;
constexpr uint32_t M_W           = 1u << 14;
constexpr uint32_t M_I           = 1u << 15;
constexpr size_t   M_RS1_BASE    = 16;
constexpr uint32_t M_B           = 1u << 21;
constexpr uint32_t M_H           = 1u << 22;
constexpr uint32_t M_SB          = 1u << 23;
constexpr size_t   M_RD_BASE     = 24;
constexpr uint32_t M_OPCODE      = 0b000 << 29;

constexpr int64_t M_MAX_OFFSET = (1 << M_OFFSET_BITS) - 1;
constexpr int64_t M_MIN_OFFSET = -M_MAX_OFFSET - 1;

constexpr size_t M_OFFSET_SIGN_BITS = UINT32_BITS - M_OFFSET_BITS;

static void calculate_offset_and_shift_m_type(int64_t value, int64_t* offset, int64_t* shamt, LineError* err) {
    if (value >= 0) {
        if (value > UINT32_MAX) goto EXCEEDS_REGISTER_WIDTH;

        uint32_t value_uint32 = (uint32_t)value;
        size_t leading_ones = __builtin_clz(~value_uint32);

        if (value <= M_MAX_OFFSET || leading_ones >= M_OFFSET_SIGN_BITS) {
            *offset = value;
            *shamt = 0;
            return;
        }

        size_t trailing_zeros = __builtin_ctz(value_uint32);
        size_t leading_zeros = __builtin_clz(value_uint32);
        size_t window_size = UINT32_BITS - leading_zeros - trailing_zeros;

        if (window_size <= M_OFFSET_BITS) {
            *shamt = M_OFFSET_SIGN_BITS - leading_zeros;
            if (*shamt > M_SHAMT_MAX) goto EXCEEDS_MAXIMUM_SHIFT;
            *offset = value_uint32 >> *shamt;
            assert(*offset <= M_MAX_OFFSET);
            return;
        }

        // Encode unsigned values that can be generated by abusing sign extentions.
        // For example: 0xFFFEA800      (or 0b1111_1111_1111_1110_1010_1000_0000_0000) can be encoded as
        //              0xFFFFFF54 << 9 (or 0b1111_1111_1111_1111_1111_1111_0101_0100 << 9).
        if (leading_zeros == 0) {
            // test whether there are enough leading zeros to accomodate the value
            *shamt = M_OFFSET_SIGN_BITS - leading_ones;
            assert(*shamt >= 0);
            if (*shamt < trailing_zeros) {
                *offset = value_uint32 >> *shamt;
                return;
            }
        }

        goto NOT_ENCODABLE;

    } else {
        if (value < INT32_MIN) goto EXCEEDS_REGISTER_WIDTH;

        if (value >= M_MIN_OFFSET) {
            *offset = value;
            *shamt = 0;
            return;
        }

        int32_t value_int32 = (int32_t)value;

        size_t trailing_zeros = __builtin_ctz(value_int32);
        size_t leading_ones = __builtin_clz(~value_int32);
        size_t window_size = INT32_BITS - leading_ones - trailing_zeros;

        if (window_size > M_OFFSET_BITS) goto NOT_ENCODABLE;

        *shamt = M_OFFSET_SIGN_BITS - leading_ones;
        assert(*shamt >= 0);
        if (*shamt > M_SHAMT_MAX) goto EXCEEDS_MAXIMUM_SHIFT;
        *offset = value_int32 >> *shamt;
        assert(*offset > M_MIN_OFFSET);
        return;
    }

EXCEEDS_REGISTER_WIDTH:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "offset exceeds register width",
        },
    };
    return;

EXCEEDS_MAXIMUM_SHIFT:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "offset encoding exceeds maximum shift amount for M-Type instructions",
        },
    };
    return;

NOT_ENCODABLE:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "offset is not encodable with 9 bit sign extended integer and shift",
        },
    };
    return;
}

Instruction encode_m_type(Tokenizer* line, uint32_t flags, StringToIntMap* defines, LineError* err) {
    StringSlice token = {};
    bool eol = false;

    uint32_t machine_word = M_OPCODE|flags;

    machine_word |= expect_register(line, err) << M_RD_BASE;
    if (err->error_tag) return (Instruction){};

    if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};
    if (!expect_token(line, TOKEN_OPEN_BRACKET, err)) return (Instruction){};
   
    machine_word |= expect_register(line, err) << M_RS1_BASE;
    if (err->error_tag) return (Instruction){};
  
    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
            },
        };
        return (Instruction){};
    }

    switch (token.bytes[0]) {
    case ']': goto WRITEBACK;
    case ',': break;
    default:
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
                .found = found_token_string(token),
            },
        };
        return (Instruction){};
    }

    // Save state of Tokenizer in case offset is immediate
    Tokenizer tokenizer_at_offset_start = *line;

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "register or expression",
            },
        };
        return (Instruction){};
    }

    int64_t offset = 0;
    int64_t shamt = 0;
    bool negative_offset = false;
    size_t offset_start_column = line->token_start;

    if (token.bytes[0] == '-') {
        negative_offset = true;
        eol = tokenizer_next(line, &token, err);
        if (err->error_tag) return (Instruction){};
        if (eol) {
            *err = (LineError){
                .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
                .unexpected_token = (LineErrorUnexpectedToken){
                    .column = line->token_start,
                    .expected = "register or expression",
                },
            };
            return (Instruction){};
        }
    }

    if (!parse_register(token, (uint64_t*)&offset)) {
        *line = tokenizer_at_offset_start;

        offset = parse_expression(line, err, defines);
        if (err->error_tag) return (Instruction){};

        calculate_offset_and_shift_m_type(offset, &offset, &shamt, err);
        if (err->error_tag) {
            err->not_encodable.start_column = offset_start_column;
            err->not_encodable.end_column = line->token_end;
            return (Instruction){};
        }

        machine_word |= M_I;
        machine_word |= (offset & M_OFFSET_MASK) << M_OFFSET_BASE;
        machine_word |= ((offset >> M_OFFSET_BITS) & 1) ? M_SB : 0;
        machine_word |= shamt << M_SHAMT_BASE;

        if (!expect_token(line, TOKEN_CLOSE_BRACKET, err)) return (Instruction){};

        goto WRITEBACK;
    }

    machine_word |= (negative_offset) ? M_SB : 0;
    machine_word |= offset << M_OFFSET_BASE;

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
            },
        };
        return (Instruction){};
    }

    switch (token.bytes[0]) {
    case ']': goto WRITEBACK;
    case 's': if (token.length == 3 && token.bytes[1] == 'l' && token.bytes[2] == 'l') break;
    default:
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "']'",
                .found = found_token_string(token),
            },
        };
        return (Instruction){};
    }

    size_t shift_start_column = tokenizer_next_token_start(line);
    shamt = parse_expression(line, err, defines);
    if (err->error_tag) return (Instruction){};
    if (shamt < 0) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NEGATIVE_SHIFT_AMOUNT,
            .negative_shift_amount = (LineErrorNegativeShiftAmount){
                .start_column = shift_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    if (shamt > M_SHAMT_MAX) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "shift value exceeds maximum shift amount for M-Type instructions",
                .start_column = shift_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    machine_word |= shamt << M_SHAMT_BASE;

    if (!expect_token(line, TOKEN_CLOSE_BRACKET, err)) return (Instruction){};

WRITEBACK:
    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) return (Instruction){ .machine_word = machine_word };

    if (token.bytes[0] != '!') {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "'eol'",
            }
        };
        return (Instruction){};
    }
    machine_word |= M_W;

    return (Instruction){ .machine_word = machine_word };
}

// ================================================================
//  Encode S-Type
// ================================================================

constexpr size_t   S_IMM_BASE = 0;
constexpr size_t   S_IMM_BITS = 8;
constexpr size_t   S_RSYS_BASE      = 8;
constexpr uint32_t S_ST             = 1u << 14;
constexpr uint32_t S_I              = 1u << 15;
constexpr size_t   S_RS1_BASE       = 16;
constexpr uint32_t S_B              = 1u << 21;
constexpr uint32_t S_H              = 1u << 22;
constexpr size_t   S_RD_BASE        = 24;
constexpr uint32_t S_OPCODE         = 0b000u << 29;

constexpr uint32_t S_RSYS_SYSCALL   = 0x3F;
constexpr int64_t S_MAX_IMM = (1 << S_IMM_BITS) - 1;

Instruction encode_lsr(Tokenizer* line, StringToIntMap* defines, LineError* err) {
    uint32_t machine_word = S_OPCODE|S_H|S_B;

    machine_word |= expect_register(line, err) << S_RD_BASE;
    if (err->error_tag) return (Instruction){};

    if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};

    size_t rsys_start_column = tokenizer_next_token_start(line);
    int64_t rsys = parse_expression(line, err, defines);
    if (err->error_tag) return (Instruction){};

    if (rsys == S_RSYS_SYSCALL) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "CSR address 63 is reserved for syscall instruction",
                .start_column = rsys_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    if (rsys < 0 || rsys > S_RSYS_SYSCALL) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "CSR address out of range (must be 0-62)",
                .start_column = rsys_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    machine_word |= rsys << S_RSYS_BASE;

    return (Instruction){ .machine_word = machine_word };
}

Instruction encode_ssr(Tokenizer* line, StringToIntMap* defines, LineError* err) {
    StringSlice token = {};
    bool eol = false;

    uint32_t machine_word = S_OPCODE|S_H|S_B|S_ST;

    machine_word |= expect_register(line, err) << S_RS1_BASE;
    if (err->error_tag) return (Instruction){};

    if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};

    Tokenizer tokenizer_at_operand_start = *line;
    size_t operand_start_column = tokenizer_next_token_start(line);

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "register or expression",
            },
        };
        return (Instruction){};
    }

    uint64_t imm = 0;

    if (!parse_register(token, &imm)) {
        *line = tokenizer_at_operand_start;

        imm = parse_expression(line, err, defines);
        if (err->error_tag) return (Instruction){};

        if (imm < 0 || imm > S_MAX_IMM) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "immediate value is not encodable with 8 bit unsigned integer",
                    .start_column = operand_start_column,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        }

        machine_word |= S_I;
    }

    machine_word |= imm << S_IMM_BASE;

    if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};

    size_t rsys_start_column = tokenizer_next_token_start(line);
    int64_t rsys = parse_expression(line, err, defines);
    if (err->error_tag) return (Instruction){};

    if (rsys == S_RSYS_SYSCALL) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "CSR address 63 is reserved for syscall instruction",
                .start_column = rsys_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    if (rsys < 0 || rsys > S_RSYS_SYSCALL) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "CSR address out of range (must be 0-62)",
                .start_column = rsys_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    machine_word |= rsys << S_RSYS_BASE;

    return (Instruction){ .machine_word = machine_word };
}

Instruction encode_syscall(Tokenizer* line, StringToIntMap* defines, LineError* err) {
    uint32_t machine_word = S_OPCODE|S_H|S_B|(S_RSYS_SYSCALL << S_RSYS_BASE);

    size_t comment_start_column = tokenizer_next_token_start(line);
    int64_t comment = parse_expression(line, err, defines);
    if (err->error_tag) return (Instruction){};

    if (comment < 0 || comment > S_MAX_IMM) {
        *err = (LineError){
            .error_tag = LINE_ERROR_NOT_ENCODABLE,
            .not_encodable = (LineErrorNotEncodable){
                .message = "comment value is not encodable with 8 bit unsigned integer",
                .start_column = comment_start_column,
                .end_column = line->token_end,
            },
        };
        return (Instruction){};
    }

    machine_word |= comment << S_IMM_BASE;

    return (Instruction){ .machine_word = machine_word };
}

// ================================================================
//  Encode I-Type
// ================================================================

constexpr size_t   I_IMM_BASE = 0;
constexpr size_t   I_IMM_BITS = 23;
constexpr uint32_t I_IMM_MASK  = 0x00FFFFFF;
constexpr uint32_t I_SIGN_MASK = 0xFF800000;
constexpr size_t   I_RD_BASE  = 24;
constexpr uint32_t I_OPCODE = 0b001u << 29;

constexpr int64_t  I_MAX_IMM = (1 << I_IMM_BITS) - 1;
constexpr int64_t  I_MIN_IMM = -I_MAX_IMM - 1;

Instruction encode_i_type(Tokenizer* line, StringToIntMap* defines, LineError* err) {
    uint32_t machine_word = I_OPCODE;

    machine_word |= expect_register(line, err) << I_RD_BASE;
    if (err->error_tag) return (Instruction){};

    if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};
    size_t imm_start_column = tokenizer_next_token_start(line);

    int64_t imm = parse_expression(line, err, defines);
    if (err->error_tag) return (Instruction){};

    if (imm >= 0) {
        if (imm > UINT32_MAX) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "immediate value exceeds register width",
                    .start_column = imm_start_column,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        }
        if (imm > I_MAX_IMM && ((imm & I_SIGN_MASK) != I_SIGN_MASK)) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "immediate value is not encodable with 24 bit sign extended integer",
                    .start_column = imm_start_column,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        }
    } else {
        if (imm < INT32_MIN) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "immediate value exceeds register width",
                    .start_column = imm_start_column,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        }
        if (imm < I_MIN_IMM) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "immediate value is not encodable with 24 bit sign extended integer",
                    .start_column = imm_start_column,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        }
    }

    machine_word |= (imm & I_IMM_MASK) << I_IMM_BASE;

    return (Instruction){ .machine_word = machine_word };
}

// ================================================================
//  Encode D-Type
// ================================================================

constexpr size_t   D_RS2_BASE   = 0;
constexpr size_t   D_IMM_BASE   = D_RS2_BASE;
constexpr size_t   D_IMM_BITS   = 8;
constexpr uint32_t D_IMM_MASK   = 0xFF;
constexpr size_t   D_SHAMT_BASE = 8;
constexpr size_t   D_SHAMT_MAX  = 31;
constexpr size_t   D_C          = 1u << 7;
constexpr uint32_t D_A          = 1u << 13;
constexpr uint32_t D_D          = 1u << 14;
constexpr uint32_t D_I          = 1u << 15;
constexpr size_t   D_RS1_BASE   = 16;
constexpr uint32_t D_FUNC_BASE  = 21;
constexpr uint32_t D_SB         = 1u << 23;
constexpr size_t   D_RD_BASE    = 24;
constexpr uint32_t D_H          = 1u << 31;
constexpr uint32_t D_OPCODE     = 0b010u << 29;

constexpr int64_t D_MAX_IMM = (1 << D_IMM_BITS) - 1;
constexpr int64_t D_MIN_IMM = -D_MAX_IMM - 1;

constexpr size_t D_IMM_SIGN_BITS = UINT32_BITS - D_IMM_BITS;

typedef enum : uint32_t {
    D_FUNC_ADD = 0b00 << D_FUNC_BASE,
    D_FUNC_XOR = 0b01 << D_FUNC_BASE,
    D_FUNC_AND = 0b10 << D_FUNC_BASE,
    D_FUNC_OR  = 0b11 << D_FUNC_BASE,
} DFunc;

typedef enum {
    D_VARIANT_BASIC,
    D_VARIANT_NOP,
    D_VARIANT_NO_RD,
    D_VARIANT_NO_RS1,
    D_VARIANT_NO_RS2,
} DVariant;

static void calculate_offset_and_shift_d_type(int64_t value, int64_t* imm, int64_t* shamt, LineError* err) {
    if (value >= 0) {
        if (value > UINT32_MAX) goto EXCEEDS_REGISTER_WIDTH;

        uint32_t value_uint32 = (uint32_t)value;
        size_t leading_ones = __builtin_clz(~value_uint32);

        if (value <= D_MAX_IMM || leading_ones >= D_IMM_SIGN_BITS) {
            *imm = value;
            *shamt = 0;
            return;
        }

        size_t trailing_zeros = __builtin_ctz(value_uint32);
        size_t leading_zeros = __builtin_clz(value_uint32);
        size_t window_size = UINT32_BITS - leading_zeros - trailing_zeros;

        if (window_size <= D_IMM_BITS) {
            *shamt = D_IMM_SIGN_BITS - leading_zeros;
            if (*shamt > D_SHAMT_MAX) goto EXCEEDS_MAXIMUM_SHIFT;
            *imm = value_uint32 >> *shamt;
            assert(*imm <= D_MAX_IMM);
            return;
        }

        // Encode unsigned values that can be generated by abusing sign extentions.
        // For example: 0xFFFEA800      (or 0b1111'1111'1111'1110'1010'1000'0000'0000) can be encoded as
        //              0xFFFFFF54 << 9 (or 0b1111'1111'1111'1111'1111'1111'0101'0100 << 9).
        if (leading_zeros == 0) {
            // test whether there are enough leading zeros to accomodate the value
            *shamt = M_OFFSET_SIGN_BITS - leading_ones;
            assert(*shamt >= 0);
            if (*shamt < trailing_zeros) {
                *imm = value_uint32 >> *shamt;
                return;
            }
        }

        goto NOT_ENCODABLE;

    } else {
        if (value < INT32_MIN) goto EXCEEDS_REGISTER_WIDTH;

        if (value >= M_MIN_OFFSET) {
            *imm = value;
            *shamt = 0;
            return;
        }

        int32_t value_int32 = (int32_t)value;

        size_t trailing_zeros = __builtin_ctz(value_int32);
        size_t leading_ones = __builtin_clz(~value_int32);
        size_t window_size = INT32_BITS - leading_ones - trailing_zeros;

        if (window_size > D_IMM_BITS) goto NOT_ENCODABLE;

        *shamt = D_IMM_SIGN_BITS - leading_ones;
        assert(*shamt >= 0);
        if (*shamt > D_SHAMT_MAX) goto EXCEEDS_MAXIMUM_SHIFT;
        *imm = value_int32 >> *shamt;
        assert(*imm > D_MIN_IMM);
        return;
    }

EXCEEDS_REGISTER_WIDTH:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "immediate value exceeds register width",
        },
    };
    return;

EXCEEDS_MAXIMUM_SHIFT:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "immediate value encoding exceeds maximum shift amount for D-Type instructions",
        },
    };
    return;

NOT_ENCODABLE:
    *err = (LineError){
        .error_tag = LINE_ERROR_NOT_ENCODABLE,
        .not_encodable = (LineErrorNotEncodable){
            .message = "immediate value is not encodable with 9 bit sign extended integer and shift",
        },
    };
    return;

}

Instruction encode_d_type(Tokenizer* line, uint32_t flags, DVariant variant, StringToIntMap* defines, LineError* err) {
    StringSlice token = {};
    bool eol = false;

    uint32_t machine_word = D_OPCODE|flags;

    if (variant == D_VARIANT_NOP) return (Instruction){ .machine_word = machine_word };

    if (variant != D_VARIANT_NO_RD) { // All except tst, teq, cmp, cpn
        machine_word |= expect_register(line, err) << D_RD_BASE;
        if (err->error_tag) return (Instruction){};
        if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};
    }

    if (variant == D_VARIANT_NO_RS1) { // sll, srl, sra, sllk
        machine_word |= expect_register(line, err) << D_RS2_BASE;
        if (err->error_tag) return (Instruction){};
        if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};
    } else {
        machine_word |= expect_register(line, err) << D_RS1_BASE;
        if (err->error_tag) return (Instruction){};

        if (variant == D_VARIANT_NO_RS2) { // mov, not
            return (Instruction){ .machine_word = machine_word };
        }

        if (!expect_token(line, TOKEN_COMMA, err)) return (Instruction){};

        // Save state of Tokenizer in case of immediate value
        Tokenizer tokenizer_at_offset_start = *line;

        eol = tokenizer_next(line, &token, err);
        if (err->error_tag) return (Instruction){};
        if (eol) {
            *err = (LineError){
                .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
                .unexpected_token = (LineErrorUnexpectedToken){
                    .column = line->token_start,
                    .expected = "register or expression",
                },
            };
            return (Instruction){};
        }

        int64_t imm = 0;
        int64_t shamt = 0;
        size_t imm_start_column = line->token_start;

        if (!parse_register(token, (uint64_t*)&imm)) {
            if (machine_word & D_C) { // adc, sbc
                *err = (LineError){
                    .error_tag = LINE_ERROR_NOT_ENCODABLE,
                    .not_encodable = (LineErrorNotEncodable){
                        .message = "carry-in arithmetic instruction with immediate value is not encodable",
                        .start_column = imm_start_column,
                        .end_column = line->token_end,
                    },
                };
                return (Instruction){};
            }

            *line = tokenizer_at_offset_start;

            imm = parse_expression(line, err, defines);
            if (err->error_tag) return (Instruction){};

            if (machine_word & D_SB) { // sub, cmp
                machine_word &= ~D_SB;
                imm = -imm;
            }

            calculate_offset_and_shift_d_type(imm, &imm, &shamt, err);
            if (err->error_tag) {
                err->not_encodable.start_column = imm_start_column;
                err->not_encodable.end_column = line->token_end;
                return (Instruction){};
            }

            machine_word |= D_I;
            machine_word |= (imm & D_IMM_MASK) << D_IMM_BASE;
            machine_word |= ((imm >> D_IMM_BITS) & 1) ? D_SB : 0;
            machine_word |= shamt << D_SHAMT_BASE;

            return (Instruction){ .machine_word = machine_word };
        }

        machine_word |= imm << D_RS2_BASE;

        eol = tokenizer_next(line, &token, err);
        if (err->error_tag) return (Instruction){};
        if (eol) {
            return (Instruction){ .machine_word = machine_word };
        }

        uint32_t shift_type = 0;
        Mnemonic mnem = parse_mnemonic(token);
        switch (mnem) {
        case MN_SLL: shift_type = 0;       break;
        case MN_SRL: shift_type = D_D;     break;
        case MN_SRA: shift_type = D_D|D_A; break;
        default:
            *err = (LineError){
                .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
                .unexpected_token = (LineErrorUnexpectedToken){
                    .column = line->token_start,
                    .expected = "'eol'",
                    .found = found_token_string(token),
                }
            };
            return (Instruction){};
        }
        if ((shift_type & D_D) && (machine_word & D_A)) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "right shift with keep-flags instruction variant is not encodable",
                    .start_column = line->token_start,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        }
        machine_word |= shift_type;
    }

    // Save state of Tokenizer in case shift is immediate
    Tokenizer tokenizer_at_offset_start = *line;

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "register or expression",
            },
        };
        return (Instruction){};
    }

    int64_t shamt = 0;
    size_t shamt_start_column = line->token_start;

    if (!parse_register(token, (uint64_t*)&shamt)) {
        *line = tokenizer_at_offset_start;

        shamt = parse_expression(line, err, defines);
        if (err->error_tag) return (Instruction){};

        if ((shamt == 0) && (machine_word & D_D)) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .start_column = shamt_start_column,
                    .end_column = line->token_end,
                    .message = "right shift of zero is not encodable",
                },
            };
            return (Instruction){};
        }

        // Handle special case where shamt=0 encodes a 32-bit shift for srl/sra
        if ((machine_word & D_D) && (shamt == 32)) {
            shamt = 0;
        }

        if (shamt < 0) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NEGATIVE_SHIFT_AMOUNT,
                .negative_shift_amount = (LineErrorNegativeShiftAmount){
                    .start_column = shamt_start_column,
                    .end_column = line->token_end,
                },
            };

            return (Instruction){};
        }
        if (shamt > D_SHAMT_MAX) {
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .start_column = shamt_start_column,
                    .end_column = line->token_end,
                    .message = "shift value exceeds maximum shift amount for D-Type instructions",
                },
            };
            return (Instruction){};
        }

        machine_word |= shamt << D_SHAMT_BASE;

        return (Instruction){ .machine_word = machine_word };
    }

    machine_word |= D_H;
    machine_word |= shamt << D_SHAMT_BASE;
    return (Instruction){ .machine_word = machine_word };
}

// ================================================================
//  Encode B-Type
// ================================================================

constexpr size_t   B_RS1_BASE  = 16;
constexpr uint32_t B_COND_BASE = 24;
constexpr uint32_t B_L         = 1u << 27;
constexpr uint32_t B_I         = 1u << 28;
constexpr uint32_t B_OPCODE    = 0b100u << 29;

typedef enum : uint32_t {
    B_COND_EQ = 0b000 << B_COND_BASE,
    B_COND_NE = 0b001 << B_COND_BASE,
    B_COND_LT = 0b010 << B_COND_BASE,
    B_COND_GE = 0b011 << B_COND_BASE,
    B_COND_LO = 0b100 << B_COND_BASE,
    B_COND_HS = 0b101 << B_COND_BASE,
    B_COND_MI = 0b110 << B_COND_BASE,
    B_COND_AL = 0b111 << B_COND_BASE,
} BCond;

Instruction encode_b_type(Tokenizer* line, uint32_t flags, LineError* err) {
    StringSlice token = {};
    bool eol = false;

    uint32_t machine_word = B_OPCODE|flags;

    // Save state of Tokenizer in case offset is label
    Tokenizer tokenizer_at_offset_start = *line;

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "register or label",
            },
        };
        return (Instruction){};
    }

    int64_t rs1 = 0;
    if (!parse_register(token, (uint64_t*)&rs1)) {
        *line = tokenizer_at_offset_start;

        StringSlice label = expect_label(line, err);
        if (err->error_tag) return (Instruction){};

        machine_word |= B_I;

        return (Instruction){
            .machine_word = machine_word,
            .label = label,
        };
    }

    machine_word |= rs1 << B_RS1_BASE;
    return (Instruction){ .machine_word = machine_word };
}

// ================================================================
//  Encode Instruction
// ================================================================

Instruction encode_instruction(Tokenizer* line, StringToIntMap* defines, LineError* err) {
    StringSlice token = {};
    bool eol = tokenizer_next(line, &token, err);
    if (eol) return (Instruction){};

    Mnemonic mnem = parse_mnemonic(token);

    Instruction encoding = (Instruction){};
    switch (mnem) {
        // M-Type
        case MN_LW:  encoding = encode_m_type(line, 0,        defines, err); break;
        case MN_LB:  encoding = encode_m_type(line, M_B,      defines, err); break;
        case MN_LH:  encoding = encode_m_type(line, M_H,      defines, err); break;
        case MN_LBU: encoding = encode_m_type(line, M_B|M_U,  defines, err); break;
        case MN_LHU: encoding = encode_m_type(line, M_H|M_U,  defines, err); break;
        case MN_SW:  encoding = encode_m_type(line, M_ST,     defines, err); break;
        case MN_SB:  encoding = encode_m_type(line, M_ST|M_B, defines, err); break;
        case MN_SH:  encoding = encode_m_type(line, M_ST|M_H, defines, err); break;
        // S-Type
        case MN_LSR: encoding = encode_lsr(line, defines, err); break;
        case MN_SSR: encoding = encode_ssr(line, defines, err); break;
        case MN_SYSCALL: encoding = encode_syscall(line, defines, err); break;
        // I-Type
        case MN_MVI: encoding = encode_i_type(line, defines, err); break;
        // D-Type
        case MN_ADD:  encoding = encode_d_type(line, D_FUNC_ADD,                     D_VARIANT_BASIC,  defines, err); break;
        case MN_ADC:  encoding = encode_d_type(line, D_FUNC_ADD         |D_C,        D_VARIANT_BASIC,  defines, err); break;
        case MN_SUB:  encoding = encode_d_type(line, D_FUNC_ADD|D_SB,                D_VARIANT_BASIC,  defines, err); break;
        case MN_SBC:  encoding = encode_d_type(line, D_FUNC_ADD|D_SB    |D_C,        D_VARIANT_BASIC,  defines, err); break;
        case MN_AND:  encoding = encode_d_type(line, D_FUNC_AND,                     D_VARIANT_BASIC,  defines, err); break;
        case MN_OR:   encoding = encode_d_type(line, D_FUNC_OR,                      D_VARIANT_BASIC,  defines, err); break;
        case MN_XOR:  encoding = encode_d_type(line, D_FUNC_XOR,                     D_VARIANT_BASIC,  defines, err); break;
        case MN_ADDK: encoding = encode_d_type(line, D_FUNC_ADD     |D_A,            D_VARIANT_BASIC,  defines, err); break;
        case MN_ADCK: encoding = encode_d_type(line, D_FUNC_ADD     |D_A|D_C,        D_VARIANT_BASIC,  defines, err); break;
        case MN_SUBK: encoding = encode_d_type(line, D_FUNC_ADD|D_SB|D_A,            D_VARIANT_BASIC,  defines, err); break;
        case MN_SBCK: encoding = encode_d_type(line, D_FUNC_ADD|D_SB|D_A|D_C,        D_VARIANT_BASIC,  defines, err); break;
        case MN_ANDK: encoding = encode_d_type(line, D_FUNC_AND     |D_A,            D_VARIANT_BASIC,  defines, err); break;
        case MN_ORK:  encoding = encode_d_type(line, D_FUNC_OR      |D_A,            D_VARIANT_BASIC,  defines, err); break;
        case MN_XORK: encoding = encode_d_type(line, D_FUNC_XOR     |D_A,            D_VARIANT_BASIC,  defines, err); break;

        case MN_TST:  encoding = encode_d_type(line, D_FUNC_AND,                     D_VARIANT_NO_RD,  defines, err); break;
        case MN_TEQ:  encoding = encode_d_type(line, D_FUNC_XOR,                     D_VARIANT_NO_RD,  defines, err); break;
        case MN_CMP:  encoding = encode_d_type(line, D_FUNC_ADD|D_SB,                D_VARIANT_NO_RD,  defines, err); break;
        case MN_CPN:  encoding = encode_d_type(line, D_FUNC_ADD,                     D_VARIANT_NO_RD,  defines, err); break;

        case MN_SLL:  encoding = encode_d_type(line, D_FUNC_ADD,                     D_VARIANT_NO_RS1, defines, err); break;
        case MN_SRL:  encoding = encode_d_type(line, D_FUNC_ADD|D_D,                 D_VARIANT_NO_RS1, defines, err); break;
        case MN_SRA:  encoding = encode_d_type(line, D_FUNC_ADD|D_D|D_A,             D_VARIANT_NO_RS1, defines, err); break;
        case MN_SLLK: encoding = encode_d_type(line, D_FUNC_ADD|    D_A,             D_VARIANT_NO_RS1, defines, err); break;

        case MN_MOV:  encoding = encode_d_type(line, D_FUNC_ADD|D_A,                 D_VARIANT_NO_RS2, defines, err); break;
        case MN_NOT:  encoding = encode_d_type(line, D_FUNC_XOR|D_SB|D_I|D_IMM_MASK, D_VARIANT_NO_RS2, defines, err); break;

        case MN_NOP:  encoding = encode_d_type(line, D_FUNC_ADD|D_A,                 D_VARIANT_NOP,    defines, err); break;
        case MN_SRLK:
        case MN_SRAK:
            *err = (LineError){
                .error_tag = LINE_ERROR_NOT_ENCODABLE,
                .not_encodable = (LineErrorNotEncodable){
                    .message = "keep-flags variant of right shift instruction is not encodable",
                    .start_column = line->token_start,
                    .end_column = line->token_end,
                },
            };
            return (Instruction){};
        // B-Type
        case MN_B:    encoding = encode_b_type(line, B_COND_AL,     err); break;
        case MN_BEQ:  encoding = encode_b_type(line, B_COND_EQ,     err); break;
        case MN_BNE:  encoding = encode_b_type(line, B_COND_NE,     err); break;
        case MN_BLT:  encoding = encode_b_type(line, B_COND_LT,     err); break;
        case MN_BGE:  encoding = encode_b_type(line, B_COND_GE,     err); break;
        case MN_BLO:  encoding = encode_b_type(line, B_COND_LO,     err); break;
        case MN_BHS:  encoding = encode_b_type(line, B_COND_HS,     err); break;
        case MN_BMI:  encoding = encode_b_type(line, B_COND_MI,     err); break;
        case MN_BL:   encoding = encode_b_type(line, B_COND_AL|B_L, err); break;
        case MN_BLEQ: encoding = encode_b_type(line, B_COND_EQ|B_L, err); break;
        case MN_BLNE: encoding = encode_b_type(line, B_COND_NE|B_L, err); break;
        case MN_BLLT: encoding = encode_b_type(line, B_COND_LT|B_L, err); break;
        case MN_BLGE: encoding = encode_b_type(line, B_COND_GE|B_L, err); break;
        case MN_BLLO: encoding = encode_b_type(line, B_COND_LO|B_L, err); break;
        case MN_BLHS: encoding = encode_b_type(line, B_COND_HS|B_L, err); break;
        case MN_BLMI: encoding = encode_b_type(line, B_COND_MI|B_L, err); break;
        default: return (Instruction){};
    }

    eol = tokenizer_next(line, &token, err);
    if (err->error_tag) return (Instruction){};
    if (!eol) {
        *err = (LineError){
            .error_tag = LINE_ERROR_UNEXPECTED_TOKEN,
            .unexpected_token = (LineErrorUnexpectedToken){
                .column = line->token_start,
                .expected = "'eol'",
                .found = found_token_string(token),
            },
        };
        return (Instruction){};
    }

    return encoding;
}
